services:
  mdm_hub:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: mdm_hub
    volumes:
      - mdm_hub:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: unless-stopped
    container_name: cloudbeaver
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      mdm_hub:
        condition: service_healthy

volumes:
  mdm_hub:

networks:
  internal:
    driver: bridge
