CREATE SCHEMA master;

CREATE TYPE master.user_role AS ENUM ('seller', 'buyer', 'admin');

CREATE TABLE master.users (
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name     VARCHAR(100)  NOT NULL,
    email         VARCHAR(100)  NOT NULL UNIQUE,
    phone         VARCHAR(20)   NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    role          master.user_role NOT NULL,
    is_active     BOOLEAN       DEFAULT TRUE,
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE master.business_profiles (
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id          BIGINT NOT NULL UNIQUE,
    farm_name        VARCHAR(150) NOT NULL,
    land_certificate VARCHAR(100),
    address          TEXT NOT NULL,
    city_id          VARCHAR(50) NOT NULL,
    province_id      VARCHAR(50) NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bp_user FOREIGN KEY (user_id)
        REFERENCES master.users(id),

    CONSTRAINT fk_bp_city FOREIGN KEY (city_id)
        REFERENCES reference.cities(id),

    CONSTRAINT fk_bp_province FOREIGN KEY (province_id)
        REFERENCES reference.provinces(id)
);


CREATE TABLE master.products (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    seller_id       BIGINT NOT NULL,
    category_id     BIGINT NOT NULL,
    name            VARCHAR(150) NOT NULL,
    description     TEXT,
    unit_id         INT NOT NULL,
    min_order_qty   DECIMAL(10,2) NOT NULL DEFAULT 0,
    price_per_unit  DECIMAL(12,2) NOT NULL,
    stock_quantity  DECIMAL(10,2) NOT NULL DEFAULT 0,
    is_negotiable   BOOLEAN NOT NULL DEFAULT FALSE,
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_prod_seller FOREIGN KEY (seller_id)
        REFERENCES master.users(id),

    CONSTRAINT fk_prod_category FOREIGN KEY (category_id)
        REFERENCES reference.product_categories(id),

    CONSTRAINT fk_prod_unit FOREIGN KEY (unit_id)
        REFERENCES reference.units(id)
);